language: java
dist: trusty
os: linux

jdk:
- oraclejdk8
- openjdk8

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"

install: true
script: ./mvnw verify --show-version --batch-mode --errors --settings .mvn/settings.xml

